import { StyleSheet } from 'react-native'
// import * as Util from '../../../../utils/constUtil'
import { scaleSize,setSpText, constUtil as Util } from '../../../../utils'
import { color, size, zIndexLevel } from '../../../../styles'
import { Const } from '../../../../constants'
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
    alignSelf: 'stretch',
  },
  pop: {
    position: 'absolute',
    left: 0,
    bottom: 0.75 * 1.4 * 0.1 * Util.WIDTH + 5,
    backgroundColor: 'white',
  },
  measureResultContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 20,
    backgroundColor: 'transparent',
    height: scaleSize(80),
    justifyContent: 'center',
    alignItems: 'center',
  },
  measureResultView: {
    minWidth: scaleSize(120),
    height: scaleSize(80),
    paddingHorizontal: scaleSize(10),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: color.transView,
  },
  measureResultText: {
    fontSize: size.fontSize.fontSizeLg,
    color: color.fontColorBlack,
  },
  mapMenu: {
    width: '100%',
    borderBottomWidth: scaleSize(3),
    borderColor: '#E8E8E8',
    backgroundColor: 'white',
    alignSelf: 'center',
    paddingVertical: scaleSize(10),
  },
  mapMenuOverlay: {
    // flex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 1,
    backgroundColor: '#rgba(0, 0, 0, 0.3)',
  },
  cutline: {
    width: '100%',
    backgroundColor: '#E8E8E8',
    height: scaleSize(3),
    marginVertical: scaleSize(10),
  },
  changeLayerBtn: {
    position: 'absolute',
    // flexDirection: 'column',
    // left: 0,
    right: scaleSize(20),
    bottom: scaleSize(200),
    backgroundColor: 'transparent',
  },
  changeLayerImage: {
    height: scaleSize(60),
    width: scaleSize(60),
  },
  popView: {
    position: 'absolute',
    flexDirection: 'column',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'white',
  },

  leftToolbar: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: scaleSize(100),
    width: scaleSize(100),
    backgroundColor: color.theme,
  },
  headerBtnSeparator: {
    marginLeft: scaleSize(40),
  },
  headerBtnTitle: {
    color: color.fontColorBlack,
    fontSize: size.fontSize.fontSizeXXl,
  },

  mapController: {
    position: 'absolute',
    left: scaleSize(20),
    bottom: scaleSize(120),
  },
  headerBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    height: scaleSize(80),
    width: scaleSize(80),
  },
  headerBtnImg: {
    height: scaleSize(60),
    width: scaleSize(60),
  },
  editControllerView: {
    flexDirection: 'row',
    // height: scaleSize(100),
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: color.contentColorWhite,
  },
  button: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  progressView: {
    position: 'absolute',
    height: 20,
    top: 0,
    left: 0,
    right: 0,
    zIndex: zIndexLevel.FIVE,
    backgroundColor: '#rgba(0, 0, 0, 0.3)',
  },
  search: {
    width: scaleSize(40),
    height: scaleSize(40),
  },
  iconAr: {
    position: 'absolute',
    right: scaleSize(20),
    borderRadius: scaleSize(4),
    elevation: 20,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 2,
    bottom: scaleSize(135),
    // backgroundColor: 'transparent',
    backgroundColor: color.white,
  },
  iconSap: {
    position: 'absolute',
    right: scaleSize(20),
    borderRadius: scaleSize(60),
    bottom: scaleSize(135),
  },
  btn: {
    backgroundColor: 'white',
    borderRadius: scaleSize(4),
  },
  shadow: {
    elevation: 20,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 2,
  },
  themeoverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0)',
    // zIndex: zIndexLevel.FOUR,
  },
  navigation: {
    backgroundColor: 'transparent',
    bottom: scaleSize(150),
    position: 'absolute',
    alignSelf: 'center',
  },
  arnavigation: {
    backgroundColor: 'transparent',
    bottom: scaleSize(300),
    right: scaleSize(31),
    position: 'absolute',
    alignSelf: 'center',
  },
  iconNav: {
    borderRadius: scaleSize(4),
    elevation: 20,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 2,
    backgroundColor: color.contentWhite,
  },
  dialogStyle: {
    // height: scaleSize(160),
  },
  dialogHeaderImg: {
    width: scaleSize(80),
    height: scaleSize(80),
  },
  dialogBackground: {
    height: scaleSize(350),
  },
  dialogOneLine: {
    height: scaleSize(270),
  },
  promptTitle: {
    fontSize: size.fontSize.fontSizeXXl,
    color: color.theme_white,
    marginTop: scaleSize(5),
    marginLeft: scaleSize(10),
    marginRight: scaleSize(10),
    textAlign: 'center',
  },
  promptTitleSmallText: {
    fontSize: size.fontSize.fontSizeLg,
    color: color.theme_white,
    marginTop: scaleSize(5),
    marginLeft: scaleSize(10),
    marginRight: scaleSize(10),
    textAlign: 'center',
  },
  dialogHeaderView: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: scaleSize(30),
  },

  item: {
    width: '100%',
    height: scaleSize(80),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: color.white,
  },
  itemtitle: {
    fontSize: scaleSize(20),
    color: color.black,
    paddingLeft: scaleSize(15),
    paddingRight: scaleSize(15),
    backgroundColor: color.white,
  },
  itemInput: {
    width: '100%',
    // height: scaleSize(120),
    fontSize: scaleSize(22),
    padding: scaleSize(15),

    // textAlignVertical: 'center',

    backgroundColor: color.white,
  },
  textConfirm: {
    fontSize: scaleSize(22),
    color: color.black,
    padding: scaleSize(10),
  },
  incrementContent: {
    width: scaleSize(500),
    height: scaleSize(300),
    backgroundColor: color.background,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: scaleSize(20),
  },
  incrementButton: {
    width: scaleSize(200),
    height: scaleSize(260),
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  incrementImage: {
    width: scaleSize(200),
    height: scaleSize(200),
  },
  incrementText: {
    fontSize: scaleSize(20),
  },
  hidden: {
    position: 'absolute',
    left: -99999,
    height: '100%',
    width: '100%',
  },
  chatBtn: {
    position: 'absolute',
    left: scaleSize(10),
    top: scaleSize(200),
    backgroundColor: '#4680DF',
    height: scaleSize(50),
    width: scaleSize(200),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scaleSize(10),
  },
  chatBtnText: {
    padding: 0,
    fontSize: size.fontSize.fontSizeLg,
    color: color.white,
  },
  addcaptureView: {
    position: 'absolute',
    width: 80,
    height: 80,
    bottom: Const.BOTTOM_HEIGHT+scaleSize(150)+scaleSize(110),
    left: '50%',
    marginLeft: -40,
    // backgroundColor: 'white',
    backgroundColor: 'transparent',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: zIndexLevel.SYSTEM,
  },
  addcapture:{
    position: 'absolute',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf:'center',
  },
  addText: {
    fontSize: setSpText(30),
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop:-scaleSize(10),
  },
  addiconView: {
    width: scaleSize(180),
    height: scaleSize(180),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  capture: {
    position: 'absolute',
    width: 80,
    height: 80,
    bottom: Const.BOTTOM_HEIGHT+scaleSize(150),
    left: '50%',
    marginLeft: -40,
    // backgroundColor: 'white',
    backgroundColor: 'transparent',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: zIndexLevel.SYSTEM,
  },
  iconView: {
    width: scaleSize(120),
    height: scaleSize(120),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  dioLog: {
    fontSize: setSpText(25),
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: 'transparent',
    maxWidth: scaleSize(300),
  },
  dioimg: {
    width: scaleSize(120),
    height: scaleSize(120),
  },
  smallIcon: {
    width: scaleSize(50),
    height: scaleSize(50),
  },
  currentHeightChangeView: {
    position: 'absolute',
    flexDirection: 'column',
    height: scaleSize(140),
    minWidth: '100%',
    backgroundColor: '#rgba(200, 200, 200, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    top: scaleSize(100),
  },
  titleCurrentHeight: {
    // height: scaleSize(45),
    // minWidth: scaleSize(180),
    fontSize: setSpText(42),
    // backgroundColor: '#rgba(45, 45, 47, 0.5)',
    color: '#FFFFFF',
    paddingLeft: 5,
    paddingRight: 5,
    textAlign: 'left',
  },
  switchARBtn: {
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchARImg: {
    width: scaleSize(120),
    height: scaleSize(120),
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomInfoTextContainer: {
    position: 'absolute',
    bottom: scaleSize(100),
    right: scaleSize(20),
    justifyContent: 'center',
    alignItems: 'flex-end',
    backgroundColor: 'transparent'
  },
  bottomInfoText:{
    color:"#fff",
    fontSize: scaleSize(16),
    textShadowOffset:{
      width:scaleSize(1),
      hegith:scaleSize(1),
    },
    textShadowRadius:scaleSize(1),
    textShadowColor:'#000'
  },
})
