export const ar_poi = require('./icon_ar_poi.png')
export const ar_3d = require('./icon_ar_3d.png')
export const ar_vector= require('./icon_ar_vector_layer.png')
export const ar_model= require('./icon_ar_model.png')
export const ar_effect = require('./icon_ar_special_effects.png')

export const ar_video = require('./icon_ar_video_Temp.png')
export const ar_picture = require('./icon_ar_picture_Temp.png')
export const ar_webvew = require('./icon_ar_webpage_Temp.png')
export const ar_text = require('./icon_ar_written_words_Temp.png')

export const ar_move = require('./icon_ar_translation.png')
export const ar_rotate = require('./icon_ar_rotate.png')
export const ar_translation = require('./icon_ar_translation.png')
export const ar_animation_none = require('./icon_ar_nothing.png')
export const ar_scale = require('./icon_ar_zoom.png')
export const ar_opacity = require('./icon_ar_opacity.png')
export const ar_border_width = require('./icon_ar_border_width.png')
export const ar_light = require('./icon_ar_light.png')
export const ar_play = require('./icon_ar_play.png')
export const ar_distance = require('./icon_ar_distance.png')

export const ar_add_location = require('./icon_ar_add_location.png')
export const ar_add_point = require('./icon_ar_add_point.png')
export const icon_add_to = require('./icon_add_to.png')

export const translation_x = require('./icon_ar_x_translation.png')
export const translation_y = require('./icon_ar_y_translation.png')
export const translation_z = require('./icon_ar_z_translation.png')

export const rotation_x = require('./icon_ar_x_rotate.png')
export const rotation_y = require('./icon_ar_y_rotate.png')
export const rotation_z = require('./icon_ar_z_rotate.png')

export const ar_animation = require('./icon_tool_deduction.png')