/**
 * iTablet自带首页模块类型
 * 顺序和显示顺序一致
 */
export default {
  MAP_EDIT: 'MAP_EDIT',
  MAP_3D: 'MAP_3D',
  MAP_COLLECTION: 'MAP_COLLECTION',
  MAP_AR: 'MAP_AR',
  MAP_NAVIGATION: 'MAP_NAVIGATION',
  MAP_THEME: 'MAP_THEME',
  MAP_PLOTTING: 'MAP_PLOTTING',
  MAP_ANALYST: 'MAP_ANALYST',
}
