/**
 * iTablet自带首页模块类型
 */
export default {
  MAP_COLLECTION: 'MAP_COLLECTION',
  // PLOTTING: 'PLOTTING',
  MAP_EDIT: 'MAP_EDIT',
  MAP_3D: 'MAP_3D',
  MAP_THEME: 'MAP_THEME',
  MAP_PLOTTING: 'MAP_PLOTTING',
  PLOTTING_ANIMATION: 'PLOTTING_ANIMATION',
  MAP_ANALYST: 'MAP_ANALYST',
  NETWORK: 'NETWORK',
  MAP_AR: 'MAP_AR',
  MAP_NAVIGATION: 'MAP_NAVIGATION',
}
