
const APPLETS_LOCATION_CONST = {
  APPLETS_CALL_DETAIL_HOME: 'APPLETS_CALL_DETAIL_HOME',
  APPLETS_CHANGE_BASE_LAYER_HOME: 'APPLETS_CHANGE_BASE_LAYER_HOME',
}

export default {
  ...APPLETS_LOCATION_CONST,
}