'use strict'

import'react'
import'react-native'
import 'react-native-orientation'
import 'react-native-screens'
import 'react-native-root-toast'
import 'imobile_for_reactnative'

// import '../src/redux/store'
// import '../src/native'

// import '@react-native-async-storage/async-storage'
// import '@react-navigation/bottom-tabs'
// import '@react-navigation/elements'
// import '@react-navigation/native'
// import '@react-navigation/native-stack'
import 'immutable'
import 'react-redux'
import 'redux'
import 'redux-actions'
import 'redux-persist'
import 'redux-promise-middleware'
import 'redux-thunk'